---
abstract: ~
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Plack::Middleware::AppTimeout
name: Plack-Middleware-AppTimeout
no_index:
  directory:
    - inc
    - t
requires:
  Plack::Middleware: 0
  parent: 0
  perl: 5.8.0
version: 0.05
